### ISSUE TITLE
Tip of LambdaNet + GHC 7.10.1 does not work

### ISSUE THREAD

**Issue by taruti** [jbarrow/LambdaNet#3]
When trying to use LambdaNet tip together with GHC 7.10.1 (hmatrix tip supports GHC 7.10) first AI.DemoLayer complains about missing "RandomTransform" and "RandomGen" imports.

Subsequently AI.Network fails with:
```
AI/Network.hs:14:1:
    The associated type ‘Parameters’
    mentions none of the type or kind variables of the class ‘Network a’
    In the class declaration for ‘Network’
```

**Comment by jbarrow** [comment]
Alright, so the most recent commit should fix DemoLayer -- which is basically a scratchpad -- and I'm updating to GHC 7.10 to attempt to recreate the Network issue.

**Comment by qzchenwl** [comment]
The same with GHC 7.10.2

**Comment by jbarrow** [comment]
Should work with the newest merge.
